server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://eureka-server:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
    
spring:
  application:
    name: api-gateway

  #security:
  #  oauth2:
  #    resourceserver:
  #      jwt:
  #        #issuer-uri: http://keycloak:8080/realms/tingeso
  #        jwk-set-uri: http://keycloak:8080/realms/tingeso/protocol/openid-connect/certs
          
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: 
              - "http://localhost:3000"
              - "http://frontend"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: client-service-client
          uri: lb://client-service
          predicates:
            - Path=/api/client/**
            
        - id: client-service-fine
          uri: lb://client-service
          predicates:
            - Path=/api/fine/**
            
            
        - id: tool-service-tool
          uri: lb://tool-service
          predicates:
            - Path=/api/tool/**
        
        - id: tool-service-catalog
          uri: lb://tool-service
          predicates:
            - Path=/api/catalog/**
         
         
        - id: kardex-service
          uri: lb://kardex-service
          predicates:
            - Path=/api/kardex/**
            
        - id: fee-service
          uri: lb://fee-service
          predicates:
            - Path=/api/fee/**
        
        - id: loan-service
          uri: lb://loan-service
          predicates:
            - Path=/api/loan/**
            
        - id: report-service
          uri: lb://report-service
          predicates:
            - Path=/api/report/**
        
        
        # Agrega más rutas según tus microservicios
