server:
  port: 0

spring:
  application:
    name: client-service
  datasource:
    url: jdbc:mysql://localhost:5432/client_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
